# Generated by Django 3.2.3 on 2021-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readeraccount',
            name='prof_pic',
            field=models.ImageField(auto_created=True, blank=True, default='static/wingsApp/userHome/assets/img/portfolio/default.png', null=True, upload_to=''),
        ),
    ]
