# Generated by Django 3.2.3 on 2021-05-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0002_readeraccount_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readeraccount',
            name='prof_pic',
            field=models.ImageField(auto_created=True, blank=True, default='/img/default.png', null=True, upload_to=''),
        ),
    ]
