# Generated by Django 3.2.3 on 2021-05-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0006_auto_20210522_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rate',
        ),
    ]
