# Generated by Django 3.2.3 on 2021-05-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0007_remove_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=1, max_length=40),
        ),
    ]
