# Generated by Django 3.2.3 on 2021-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0010_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default=1, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pageNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
