# Generated by Django 3.2.3 on 2021-05-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0011_auto_20210526_2011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liked_post',
            unique_together={('note_id', 'liked_by')},
        ),
    ]
