# Generated by Django 3.2.3 on 2021-05-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0012_alter_liked_post_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='follow',
        ),
    ]
