# Generated by Django 3.2.3 on 2021-05-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0014_auto_20210529_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
