# Generated by Django 3.2.3 on 2021-05-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0016_alter_readeraccount_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readeraccount',
            name='prof_pic',
            field=models.ImageField(blank=True, default='/default.png', null=True, upload_to=''),
        ),
    ]
