# Generated by Django 3.2.3 on 2021-06-11 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0017_alter_readeraccount_prof_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrecords',
            name='headerImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='readeraccount',
            name='prof_pic',
            field=models.ImageField(blank=True, default='/default.jpg', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='readingRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromPage', models.IntegerField()),
                ('toPage', models.IntegerField()),
                ('book_shelf_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AJNIHA.shelves_readers_books')),
            ],
        ),
    ]
