# Generated by Django 3.2.3 on 2021-06-11 03:37

from django.db import migrations, models
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0018_auto_20210611_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrange',
            name='bookcompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='readingrecords',
            name='note',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
