# Generated by Django 3.2.3 on 2021-06-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0021_book_booklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(auto_created=True, blank=True, default='/book.png', null=True, upload_to=''),
        ),
    ]
