# Generated by Django 3.2.3 on 2021-06-12 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJNIHA', '0022_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrange',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 22, 17, 53, 336301)),
        ),
    ]
